[package]
name = "asn1-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
picky-asn1-der = "0.3.1"
serde = "1.0.142"
serde_bytes = "0.11.7"